"""initial migrate

Revision ID: 1a9133aefbc2
Revises: 
Create Date: 2024-04-08 17:25:31.889516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a9133aefbc2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('agent_id', sa.Integer(), nullable=False))
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Date(),
               existing_nullable=False)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('read')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('agent_id')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
